name: twin_app
description: "Boodskap Digital Twin Client Application"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  twin_commons:
    git:
      url: https://github.com/boodskap/twin_commons.git
      ref: main

#  twinned_widgets:
#    git:
#      url: https://github.com/boodskap/twinned_widgets.git
#      # path:
#      #   twinned_widgets

  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/translations/
    - assets/images/
    - assets/
    - .env
    - .env.dev
    - .env.qa
    - .env.test
    - default.conf
