name: twin_app
description: "Boodskap Digital Twin Client Application"
publish_to: 'none' 
version: 1.0.3+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  twinned_widgets:
      git:
        url: https://github.com/boodskap/twinned_widgets.git
        ref: main
  #    path:
  #      twin_commons

  pulse_admin_api:
    git:
      url: https://github.com/boodskap/pulse_admin_api.git
      ref: main

  curved_navigation_bar: ^1.0.6
  badges: ^2.0.3
  flutter_dotenv: ^5.0.2
  easy_localization: ^3.0.1
  easy_logger: ^0.0.2
  go_router: ^14.2.0
  pinput: ^4.0.0
  flutter_displaymode: ^0.6.0
  get_it: ^7.2.0
  flutter_native_splash: ^2.4.1
  font_awesome_flutter: ^10.7.0
  flutter_html: ^3.0.0-beta.2
  flutter_widget_from_html: ^0.15.1
  intl_phone_field: ^3.2.0
  #flutter_native_splash: ^2.4.0
  accordion: ^2.6.0
  dropdown_search: ^5.0.6
  code_editor: ^2.1.0
  flutter_code_editor: ^0.3.2
  highlight: ^0.7.0
  dropdown_button2: ^2.3.9
  multi_select_flutter: ^4.1.3
  string_validator: ^1.1.0
  input_quantity: ^2.4.0
  google_maps_flutter: ^2.9.0
  flutter_json_view: ^1.1.5
  timezone_dropdown: ^1.0.5
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/translations/
    - assets/images/
    - assets/.env
    - assets/.env.dev
    - assets/
    - default.conf
