name: twin_app
description: "Boodskap Digital Twin Client Application"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  eventify: ^1.0.1
  pinput: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  twinned_widgets:
    git:
      url: https://github.com/boodskap/twinned_widgets.git
  #  path:
  #    twinned_widgets


flutter:

  uses-material-design: true

  assets:
    - assets/images/
